### ISSUE TITLE
Can't run the code using CLI

### ISSUE THREAD

**Issue by hslee-lunit** [CBICA/Deep-LIBRA#4]
Hi, thanks for sharing your work!

I tried to run the code, but I failed.
The error occurs when loading the model weights here
https://github.com/CBICA/Deep-LIBRA/blob/main/load_models.py#L36-L40

I set the same environment with tensorflow 1.12 and downloaded the trained weights.
However I found that I can't load the model weights. The reason might be there is no model code as this error message says.
```
Unable to open 'encoders_seg_models.py': Unable to read file '/home/ohm/github/Odeep/encoders_seg_models.py' 
```

How can I solve this problem? Thanks in advance.

Error message:
>   File "execute_libra_code.py", line 62, in main_function
>     Info.run_air_cnn()
>   File "/lunit/home/hslee/workspace/lib/Deep-LIBRA/libra.py", line 193, in run_air_cnn
>     self.Keys_txt_file_input, self.Keys_object)
>   File "/lunit/home/hslee/workspace/lib/Deep-LIBRA/load_models.py", line 40, in get_network_segmentation
>     "sensitivity_weighted": sensitivity_weighted, "dice":dice, "dice_weighted": dice_weighted})
>   File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/engine/saving.py", line 419, in load_model
>     model = _deserialize_model(f, custom_objects, compile)
>   File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
>     model = model_from_config(model_config, custom_objects=custom_objects)
>   File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/engine/saving.py", line 458, in model_from_config
>     return deserialize(config, custom_objects=custom_objects)
>   File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/layers/__init__.py", line 55, in deserialize
>     printable_module_name='layer')
>   File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
>     list(custom_objects.items())))
>   File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/engine/network.py", line 1032, in from_config
>     process_node(layer, node_data)
>   File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/engine/network.py", line 991, in process_node
>     layer(unpack_singleton(input_tensors), **kwargs)
>   File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/engine/base_layer.py", line 457, in __call__
>     output = self.call(inputs, **kwargs)
>   File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/layers/core.py", line 687, in call
>     return self.function(inputs, **arguments)
>   File "/home/ohm/github/Odeep/encoders_seg_models.py", line 113, in <lambda>
> IndexError: tuple index out of range
>

**Comment by hslee-lunit** [comment]
@AlexanderGetka-cbica @waltman 
Sorry for pinging here. Would you kindly look into this issue?

**Comment by omaghsoudi** [comment]
> @AlexanderGetka-cbica @waltman
> Sorry for pinging here. Would you kindly look into this issue?



> Hi, thanks for sharing your work!
> 
> I tried to run the code, but I failed. The error occurs when loading the model weights here https://github.com/CBICA/Deep-LIBRA/blob/main/load_models.py#L36-L40
> 
> I set the same environment with tensorflow 1.12 and downloaded the trained weights. However I found that I can't load the model weights. The reason might be there is no model code as this error message says.
> 
> ```
> Unable to open 'encoders_seg_models.py': Unable to read file '/home/ohm/github/Odeep/encoders_seg_models.py' 
> ```
> 
> How can I solve this problem? Thanks in advance.
> 
> Error message:
> 
> > File "execute_libra_code.py", line 62, in main_function
> > Info.run_air_cnn()
> > File "/lunit/home/hslee/workspace/lib/Deep-LIBRA/libra.py", line 193, in run_air_cnn
> > self.Keys_txt_file_input, self.Keys_object)
> > File "/lunit/home/hslee/workspace/lib/Deep-LIBRA/load_models.py", line 40, in get_network_segmentation
> > "sensitivity_weighted": sensitivity_weighted, "dice":dice, "dice_weighted": dice_weighted})
> > File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/engine/saving.py", line 419, in load_model
> > model = _deserialize_model(f, custom_objects, compile)
> > File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
> > model = model_from_config(model_config, custom_objects=custom_objects)
> > File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/engine/saving.py", line 458, in model_from_config
> > return deserialize(config, custom_objects=custom_objects)
> > File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/layers/**init**.py", line 55, in deserialize
> > printable_module_name='layer')
> > File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
> > list(custom_objects.items())))
> > File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/engine/network.py", line 1032, in from_config
> > process_node(layer, node_data)
> > File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/engine/network.py", line 991, in process_node
> > layer(unpack_singleton(input_tensors), **kwargs)
> > File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/engine/base_layer.py", line 457, in **call**
> > output = self.call(inputs, **kwargs)
> > File "/lunit/home/hslee/.local/lib/python3.5/site-packages/keras/layers/core.py", line 687, in call
> > return self.function(inputs, **arguments)
> > File "/home/ohm/github/Odeep/encoders_seg_models.py", line 113, in 
> > IndexError: tuple index out of range

I think you need the networks shared [here](https://github.com/CBICA/Deep-LIBRA/issues/1).

**Comment by hslee-lunit** [comment]
@omaghsoudi
I used the weights you shared. I found that the problem is a package version mismatch.
Based on the error message, I couldn't figure it out, but good to solve this. Thanks!
